pipeline {
    agent any
    environment {
        PATH = "$PATH:/opt/apache-maven-3.8.7/bin"
    }
    stages {
        stage('GetCode') {
            steps {
                git 'https://github.com/ankureddy/DevOps.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('SonarQube analysis') {
            steps {
                script {
                    def scannerHome = tool 'sonarqube-9.6.1'
                    withSonarQubeEnv('sonarqube-9.6.1') {
                        // If you have configured more than one global server connection, you can specify its name
                        //sh "${scannerHome}/bin/sonar-scanner"
                        sh "mvn sonar:sonar"
                    }
                }
            }
        }
    }
}
